import type { Universe, Faction, Character, Location, TimelineEvent, StoryArc, LoreRule } from './types';

export const DEMO_UNIVERSE_ID = 'demo-ashen-veil-001';

export const demoUniverse: Universe = {
  id: DEMO_UNIVERSE_ID,
  name: 'The Ashen Veil',
  concept: 'An ancient empire fell when the sky split open and released memory-eating storms across the world. Now kingdoms, outlaw guilds, relic hunters, and forgotten bloodlines battle over the shattered remains of history.',
  genre: 'Fantasy',
  tone: 'Dark',
  era: 'Age of Ash — Post-Veilbreak',
  tech_level: 'Medieval',
  magic_system: 'Veilweaving — drawing on the torn fabric of the sky to reshape memory, time, and matter. Dangerous and sanity-consuming.',
  world_overview: `The world of Ashenmere was once unified under the Eternal Throne of the Solarian Empire — a civilization that mastered the art of Veilweaving, binding history itself into architecture, weapons, and flesh. When the last Emperor attempted to weave all memory into a singular, immortal Archive, the sky fractured. The Veilbreak unleashed storms of pure forgetting: entire cities vanished from history, people woke not knowing their names, and the laws of reality bent under the weight of unmade time.\n\nNow, centuries later, Ashenmere is a world of survivors and scavengers. The Ashen Storms still roam the wastelands between city-states, devouring the memories of anyone caught in them. Veilweavers are both feared and desperately sought. Fragments of the old Empire's knowledge — called Echoes — are the most precious currency in existence.\n\nFive major powers have risen from the ruins, each claiming the right to determine what history means — and what it becomes.`,
  creation_myth: `In the beginning, there was only the Veil — an infinite tapestry woven from every moment that had ever existed and every moment yet to come. The First Weavers, beings of pure intention, shaped the world from its threads.\n\nBut one Weaver, called the Unnamed, grew envious of mortality. They pulled a thread of ending from the Veil and wove it into their own heart, becoming the first to die — and the first to leave a memory behind. From that death, humanity was born: creatures who could only ever know pieces of the Veil, fragments of the eternal pattern.\n\nThe Solarian Empire believed their Emperor was the Unnamed's heir, destined to reunite all fragments. When he reached too far, the Veil did not break — it screamed. And from that scream came the Ashen Storms, the sound of forgotten things given hunger.`,
  themes: ['The price of memory', 'Power born from forgetting', 'Survival vs. truth', 'The corruption of legacy', 'Identity in a world of erasure'],
  current_conflict: 'The Shattered Crown has obtained a complete Solarian Loom — a device capable of rewriting historical canon across an entire region. If they use it, the Veil Wardens believe it will cause a Second Veilbreak. The Ashborn Guild is racing to either steal or destroy it, while the Memory Keepers argue it should be used to restore what was lost. The Storm Prophets preach that the Second Veilbreak is inevitable — and holy.',
  prophecy_hooks: [
    'The Unnamed\'s heir shall either seal the Veil or unravel it entirely — and they walk among the living now.',
    'The Seven Echo-Keys, scattered before the Veilbreak, together unlock the Archive of All Things. Three have been found. One is a person.',
    'When ash falls upward, the Forgotten Emperor walks again.',
    'The first Storm Prophet\'s journal was written in a language that did not exist until three centuries after their death.'
  ],
  created_at: '2024-01-01T00:00:00.000Z',
  updated_at: '2024-01-01T00:00:00.000Z',
};

export const demoFactions: Faction[] = [
  {
    id: 'faction-veil-wardens',
    universe_id: DEMO_UNIVERSE_ID,
    name: 'The Veil Wardens',
    type: 'Order / Military Brotherhood',
    ideology: 'The Veil must be preserved at all costs. Unauthorized Veilweaving is sacrilege. History is not a weapon.',
    leader: 'High Warden Selara Dusk',
    resources: 'Fortified citadels called Seals, ancient binding-weapons, a network of memory-locked archives, and the largest trained Veilweaver corps.',
    allies: ['The Memory Keepers (uneasy)'],
    enemies: ['The Shattered Crown', 'The Ashborn Guild', 'The Storm Prophets'],
    territory: 'The Ashspine Mountains and three major Seal-citadels across the central continent',
    internal_conflict: 'A radical splinter faction within the Wardens believes the only way to truly stop the Shattered Crown is to use the Loom themselves — once.',
    objective: 'Prevent the Shattered Crown from using the Solarian Loom. Maintain order across Veilweaving practice.',
    canon_status: 'canon',
  },
  {
    id: 'faction-ashborn-guild',
    universe_id: DEMO_UNIVERSE_ID,
    name: 'The Ashborn Guild',
    type: 'Thieves Guild / Mercenary Network',
    ideology: 'Information is survival. History belongs to those who find it. Loyalty is bought — but once bought, it holds.',
    leader: 'The Architect (identity unknown, possibly multiple people)',
    resources: 'Spy networks in every major city, stolen Echo fragments, the fastest courier network in Ashenmere, and specialized anti-Veilweaving gear.',
    allies: ['Independent city-states', 'select Memory Keepers'],
    enemies: ['The Veil Wardens', 'The Shattered Crown'],
    territory: 'No fixed territory — embedded in every major city',
    internal_conflict: 'Several senior Guild members are secretly selling information to the Shattered Crown.',
    objective: 'Acquire the Solarian Loom before the Shattered Crown can use it. Sell it to the highest bidder — or destroy it if the price is right.',
    canon_status: 'canon',
  },
  {
    id: 'faction-memory-keepers',
    universe_id: DEMO_UNIVERSE_ID,
    name: 'The Memory Keepers',
    type: 'Scholar Caste / Religious Order',
    ideology: 'Every memory is sacred. The lost past must be restored. The Veilbreak was a tragedy, not a judgment.',
    leader: 'Archivist-Prime Theo Nessian',
    resources: 'The largest collection of pre-Veilbreak texts, highly trained historian-mages, political connections across academic city-states.',
    allies: ['The Veil Wardens (formal)', 'The Ashborn Guild (informal)'],
    enemies: ['The Storm Prophets', 'The Shattered Crown'],
    territory: 'The Pale Library — a city-sized archive built on what is believed to be the site of the original Veilbreak',
    internal_conflict: 'A younger generation of Keepers believe the old hierarchy is deliberately suppressing certain memories to maintain their own power.',
    objective: 'Use the Solarian Loom to restore lost pre-Veilbreak history — specifically, to recover the names and identities of everyone erased by the Ashen Storms.',
    canon_status: 'canon',
  },
  {
    id: 'faction-shattered-crown',
    universe_id: DEMO_UNIVERSE_ID,
    name: 'The Shattered Crown',
    type: 'Fallen Royalist Empire / Cult of Legacy',
    ideology: 'The Solarian Empire must be restored. What history forgot, we shall rewrite. The Veilbreak was not a failure — it was a test.',
    leader: 'Emperor-Claimant Varro Solane (disputed bloodline)',
    resources: 'The Solarian Loom, a loyal army of Ashen Soldiers (warriors who traded their memories for fighting ability), hidden imperial vaults.',
    allies: ['The Storm Prophets (opportunistic)'],
    enemies: ['The Veil Wardens', 'The Memory Keepers', 'The Ashborn Guild'],
    territory: 'The Pale Throne — a ruined palace in the Forgetting Wastes',
    internal_conflict: 'Varro\'s own bloodline is disputed; several of his commanders privately believe the true heir is already among their enemies.',
    objective: 'Use the Loom to rewrite regional history, establishing the legitimacy of the Shattered Crown and erasing evidence of Imperial atrocities.',
    canon_status: 'canon',
  },
  {
    id: 'faction-storm-prophets',
    universe_id: DEMO_UNIVERSE_ID,
    name: 'The Storm Prophets',
    type: 'Doomsday Cult / Wandering Preachers',
    ideology: 'The Second Veilbreak is inevitable and holy. The Unnamed wishes to reclaim all threads. Resistance is vanity.',
    leader: 'The First Voice (self-styled prophet, true identity: Mirenne Ash, former Memory Keeper)',
    resources: 'Fanatical followers, ability to survive inside Ashen Storms, knowledge of Storm patterns others lack.',
    allies: ['The Shattered Crown (uneasy)'],
    enemies: ['The Veil Wardens', 'The Memory Keepers'],
    territory: 'Nomadic — follow the Ashen Storm paths',
    internal_conflict: 'Not all Prophets actually want the world to end — some are gathering Storm knowledge to find a way to stop the Second Break while maintaining their cover.',
    objective: 'Ensure the Shattered Crown uses the Loom — not to restore history, but to trigger the Second Veilbreak.',
    canon_status: 'canon',
  },
];

export const demoCharacters: Character[] = [
  {
    id: 'char-kael-ashvane',
    universe_id: DEMO_UNIVERSE_ID,
    faction_id: 'faction-ashborn-guild',
    name: 'Kael Ashvane',
    title: 'The Hollow Blade',
    role: 'Protagonist / Former Veil Warden turned Guild operative',
    motivations: 'To find his mother, whose memory was devoured by an Ashen Storm — and whose name he can no longer remember. He believes the Loom can restore her.',
    fears: 'That he will forget her face before he finds her. That she is already gone — not dead, but unmade.',
    powers: 'Former Warden training: combat, binding-seals. Partial Veilweaving ability — he can see echoes of erased memories in objects. This is technically illegal.',
    weaknesses: 'His obsession clouds judgment. He trusts the Guild too easily. His Veilweaving causes memory bleeds — he sometimes forgets recent events.',
    relationships: [
      { character_id: 'char-selara-dusk', character_name: 'Selara Dusk', type: 'rival' },
      { character_id: 'char-mirenne-ash', character_name: 'Mirenne Ash', type: 'mentor' },
      { character_id: 'char-lysa-thorne', character_name: 'Lysa Thorne', type: 'ally' },
    ],
    arc_potential: 'Discovers his mother was not simply forgotten — she was deliberately erased by the Veil Wardens as part of a cover-up. His choice to forgive or destroy the institution that raised him.',
    status: 'alive',
    canon_status: 'canon',
  },
  {
    id: 'char-selara-dusk',
    universe_id: DEMO_UNIVERSE_ID,
    faction_id: 'faction-veil-wardens',
    name: 'Selara Dusk',
    title: 'High Warden of the Third Seal',
    role: 'Antagonist-adjacent / Pragmatic moral authority',
    motivations: 'To prevent a Second Veilbreak at any cost. She has seen what the Storms do — she carries 40 years of survivor testimony.',
    fears: 'That the cost of preventing the Veilbreak will make her into the very thing she fights against.',
    powers: 'Master Veilweaver — can read the full history of any object or person with a touch. Can create binding-seals that lock memories permanently.',
    weaknesses: 'Institutional loyalty over individual justice. She knows where Kael\'s mother is — and has chosen not to tell him.',
    relationships: [
      { character_id: 'char-kael-ashvane', character_name: 'Kael Ashvane', type: 'rival' },
      { character_id: 'char-theo-nessian', character_name: 'Theo Nessian', type: 'ally' },
    ],
    arc_potential: 'Forced to choose between the institution she built and the truth she buried.',
    status: 'alive',
    canon_status: 'canon',
  },
  {
    id: 'char-varro-solane',
    universe_id: DEMO_UNIVERSE_ID,
    faction_id: 'faction-shattered-crown',
    name: 'Varro Solane',
    title: 'Emperor-Claimant of the Restored Throne',
    role: 'Primary Antagonist',
    motivations: 'To restore the Solarian Empire and prove his bloodline\'s legitimacy — by rewriting the historical record itself.',
    fears: 'That he is not actually of imperial blood — that his entire claim is a fabrication his handlers created to control him.',
    powers: 'Minimal Veilweaving — instead possesses the Solarian Loom, which amplifies any weaver\'s power to reality-altering levels.',
    weaknesses: 'His handlers (Storm Prophets) have a different agenda. He is brilliant in politics but naive about magic.',
    relationships: [
      { character_id: 'char-mirenne-ash', character_name: 'Mirenne Ash', type: 'enemy' },
      { character_id: 'char-selara-dusk', character_name: 'Selara Dusk', type: 'enemy' },
    ],
    arc_potential: 'Discovers the Prophets are using him to end the world. The question is whether he chooses to stop them — or decides the end of history is preferable to the humiliation of being nobody.',
    status: 'alive',
    canon_status: 'canon',
  },
  {
    id: 'char-lysa-thorne',
    universe_id: DEMO_UNIVERSE_ID,
    faction_id: 'faction-ashborn-guild',
    name: 'Lysa Thorne',
    title: 'The Architect\'s Voice',
    role: 'Deuteragonist / Moral compass with secrets',
    motivations: 'She is the Architect. She has been managing the Guild for seven years using multiple proxies. She wants the Loom destroyed — she has seen what it does to those who use it.',
    fears: 'That the people she has deceived will not forgive her when they learn the truth.',
    powers: 'Non-magical — elite strategist, infiltration specialist, polyglot, master of constructed identities.',
    weaknesses: 'Has too many false identities and is beginning to lose track of who she actually is.',
    relationships: [
      { character_id: 'char-kael-ashvane', character_name: 'Kael Ashvane', type: 'ally' },
      { character_id: 'char-theo-nessian', character_name: 'Theo Nessian', type: 'rival' },
    ],
    arc_potential: 'The irony of a woman obsessed with false identities in a world where identity can be literally erased.',
    status: 'alive',
    canon_status: 'canon',
  },
  {
    id: 'char-mirenne-ash',
    universe_id: DEMO_UNIVERSE_ID,
    faction_id: 'faction-storm-prophets',
    name: 'Mirenne Ash',
    title: 'The First Voice of the Storm',
    role: 'Wild card / Former ally turned apocalypse architect',
    motivations: 'She was once a Memory Keeper who tried to use a smaller Loom to restore memories — and accidentally erased an entire village. She believes she is already damned, and the Second Veilbreak will unmake her crime.',
    fears: 'Being remembered as a monster. Being forgotten entirely.',
    powers: 'Walks freely through Ashen Storms — she gave her pain to the Storms in exchange. Can command minor Storm manifestations.',
    weaknesses: 'Genuinely believes in what she preaches. Cannot be reasoned with using logic — only memory.',
    relationships: [
      { character_id: 'char-kael-ashvane', character_name: 'Kael Ashvane', type: 'mentor' },
      { character_id: 'char-varro-solane', character_name: 'Varro Solane', type: 'traitor' },
    ],
    arc_potential: 'Kael was her student. Whether she allows him to save her — or forces him to stop her — defines both their arcs.',
    status: 'alive',
    canon_status: 'canon',
  },
  {
    id: 'char-theo-nessian',
    universe_id: DEMO_UNIVERSE_ID,
    faction_id: 'faction-memory-keepers',
    name: 'Theo Nessian',
    title: 'Archivist-Prime of the Pale Library',
    role: 'Morally grey authority figure',
    motivations: 'To restore all erased memories — genuinely believes this is the most important work in the world.',
    fears: 'That some memories were erased because they deserved to be — and restoring them will prove it.',
    powers: 'Photographic recall of everything he has ever read. Can reconstruct lost texts from partial fragments.',
    weaknesses: 'Is deliberately suppressing discovery of the Suppression Logs — records showing the Wardens and Keepers cooperated to erase certain memories.',
    relationships: [
      { character_id: 'char-selara-dusk', character_name: 'Selara Dusk', type: 'ally' },
      { character_id: 'char-lysa-thorne', character_name: 'Lysa Thorne', type: 'rival' },
    ],
    arc_potential: 'The guardian of memory who is himself a censor. His arc ends when the logs are found.',
    status: 'alive',
    canon_status: 'canon',
  },
  {
    id: 'char-ashen-soldier',
    universe_id: DEMO_UNIVERSE_ID,
    faction_id: 'faction-shattered-crown',
    name: 'The Nameless General',
    title: 'Commander of the Ashen Army',
    role: 'Tragic enforcer / Mystery',
    motivations: 'Unknown — traded all personal memory for combat perfection.',
    fears: 'Unknown — no longer capable of fear in the conventional sense.',
    powers: 'Enhanced combat ability, immunity to Ashen Storm memory effects, can sense Veilweaving within 100 meters.',
    weaknesses: 'Can be manipulated through the fragments of memory they did not trade — small objects they still carry instinctively.',
    relationships: [
      { character_id: 'char-varro-solane', character_name: 'Varro Solane', type: 'ally' },
    ],
    arc_potential: 'Mystery: who were they? Several characters claim to recognize them. Solving it reveals a major pre-Veilbreak secret.',
    status: 'unknown',
    canon_status: 'mystery',
  },
  {
    id: 'char-unnamed-heir',
    universe_id: DEMO_UNIVERSE_ID,
    name: 'The Unnamed Heir',
    title: 'Unknown',
    role: 'Prophecy figure / Unknown identity',
    motivations: 'Unknown',
    fears: 'Unknown',
    powers: 'Prophecy suggests: ability to weave and unweave simultaneously — to remember and forget at will.',
    weaknesses: 'Unknown',
    relationships: [],
    arc_potential: 'The central prophecy figure. Could be any named character — or someone not yet introduced.',
    status: 'unknown',
    canon_status: 'mystery',
  },
];

export const demoLocations: Location[] = [
  {
    id: 'loc-pale-library',
    universe_id: DEMO_UNIVERSE_ID,
    name: 'The Pale Library',
    type: 'City-Archive',
    region: 'Central Ashenmere',
    description: 'A city-sized structure of white stone and memory-glass, built directly on the epicenter of the Veilbreak. The entire city functions as a living archive — every stone records what happens nearby. Entering without Memory Keeper credentials causes mild memory displacement.',
    strategic_value: 'Contains the largest collection of pre-Veilbreak knowledge. Controls access to most historical records.',
    mythic_importance: 'Built at the exact point where the sky fractured. Some scholars believe the Veilbreak is still happening here — just slowly.',
    canon_status: 'canon',
  },
  {
    id: 'loc-pale-throne',
    universe_id: DEMO_UNIVERSE_ID,
    name: 'The Pale Throne',
    type: 'Ruined Palace',
    region: 'The Forgetting Wastes',
    description: 'The shattered remains of the Solarian Imperial Palace, frozen in a permanent state of half-collapse. Ashen Storms circle it but never enter — the palace somehow repels them. The Shattered Crown uses it as their seat of power.',
    strategic_value: 'Contains hidden Imperial vaults and the throne room where the Solarian Loom is being assembled.',
    mythic_importance: 'Where the Emperor performed the ritual that caused the Veilbreak. The walls still whisper in his voice.',
    canon_status: 'canon',
  },
  {
    id: 'loc-ashspine-mountains',
    universe_id: DEMO_UNIVERSE_ID,
    name: 'The Ashspine Mountains',
    type: 'Mountain Range / Fortress Network',
    region: 'Northern Ashenmere',
    description: 'A volcanic mountain range where the Veil Wardens built their Seal-citadels into the rock itself. The mountains exhale ash constantly — it is safe to breathe but impossible to track through.',
    strategic_value: 'Three Seal-citadels, the strongest defensive positions in Ashenmere.',
    mythic_importance: 'The mountains themselves are believed to be the spine of the First Weaver — a giant who became stone to hold the world together.',
    canon_status: 'canon',
  },
  {
    id: 'loc-forgetting-wastes',
    universe_id: DEMO_UNIVERSE_ID,
    name: 'The Forgetting Wastes',
    type: 'Dangerous Wasteland',
    region: 'Central Ashenmere',
    description: 'The largest Ashen Storm territory — a permanent zone of memory-eating weather covering what was once the heart of the Solarian Empire. Cities, people, and entire ecosystems have been unmade here.',
    strategic_value: 'Contains vast pre-Veilbreak ruins — anyone who can navigate the Storms finds unimaginable treasures.',
    mythic_importance: 'The Storm Prophets believe the Wastes are where the Unnamed is being reborn.',
    canon_status: 'canon',
  },
  {
    id: 'loc-echo-market',
    universe_id: DEMO_UNIVERSE_ID,
    name: 'The Echo Market',
    type: 'Black Market City',
    region: 'Coastal Ashenmere',
    description: 'A massive floating market city built on interconnected barges, where Echo fragments are bought, sold, and gambled. No Warden jurisdiction. The Ashborn Guild effectively controls it.',
    strategic_value: 'Primary trade hub for illicit Echo fragments and historical artifacts.',
    mythic_importance: 'Said to be built over the grave of a Solarian admiral who drowned the fleet rather than let it fall to the Veilbreak.',
    canon_status: 'canon',
  },
  {
    id: 'loc-storm-path',
    universe_id: DEMO_UNIVERSE_ID,
    name: 'The Storm Pilgrimage Path',
    type: 'Sacred Route',
    region: 'Throughout Ashenmere',
    description: 'A series of way-stations and cairns marking the migration routes of the Ashen Storms. The Storm Prophets maintain these paths and offer passage to those who pay — or convert.',
    strategic_value: 'Only reliable way to move quickly through Storm-affected territory.',
    mythic_importance: 'Each cairn is built from the remains of someone who died in a Storm — their name inscribed, their memory supposedly preserved within.',
    canon_status: 'canon',
  },
  {
    id: 'loc-archive-zero',
    universe_id: DEMO_UNIVERSE_ID,
    name: 'Archive Zero',
    type: 'Lost Location',
    region: 'Unknown — possibly inside the Forgetting Wastes',
    description: 'The theoretical first archive of the Solarian Empire — believed to contain the complete pre-Veilbreak historical record, including everything the Storms erased. No confirmed sightings, but the Ashborn Guild has been selling maps to it for decades.',
    strategic_value: 'If real, it contains enough historical leverage to reshape all political power in Ashenmere.',
    mythic_importance: 'Possibly the location of the original Loom — the one the Emperor used to cause the Veilbreak.',
    canon_status: 'mystery',
  },
  {
    id: 'loc-threshold-city',
    universe_id: DEMO_UNIVERSE_ID,
    name: 'Threshold',
    type: 'Border City',
    region: 'Edge of the Forgetting Wastes',
    description: 'The last city before the Wastes. Half of its population are Storm survivors who lost varying amounts of memory. The other half are professionals who make a living processing them — memory therapists, identity reconstructors, and grief merchants.',
    strategic_value: 'Key entry point to the Wastes. All major factions have operations here.',
    mythic_importance: 'Where Kael Ashvane was found as a child, alone, with no memory of his name.',
    canon_status: 'canon',
  },
];

export const demoTimeline: TimelineEvent[] = [
  {
    id: 'event-01-empire-peak',
    universe_id: DEMO_UNIVERSE_ID,
    title: 'The Golden Apex — Solarian Empire at Full Extent',
    era_marker: 'Age of Weavers — Year 400',
    summary: 'The Solarian Empire covers two-thirds of the known world. Veilweaving is taught in academies. The Emperor announces Project Archive — an attempt to bind all living memory into a single eternal repository.',
    affected_characters: ['Emperor (unnamed)', 'First Memory Keepers (founded this era)'],
    affected_factions: ['Proto-Veil Wardens', 'Memory Keepers (founding)'],
    affected_locations: ['The Pale Library (constructed this era)', 'Ashspine Mountains (fortified this era)'],
    consequences: 'Triggers the chain of events leading to the Veilbreak. Establishes the institutions that will survive the empire.',
    canon_status: 'canon',
  },
  {
    id: 'event-02-first-dissent',
    universe_id: DEMO_UNIVERSE_ID,
    title: 'The Dissenter\'s War',
    era_marker: 'Age of Weavers — Year 412',
    summary: 'A coalition of Veilweavers who oppose Project Archive attempt a coup. The Emperor\'s response is disproportionate — he uses partial Archive power to literally erase three rebel leaders from history.',
    affected_characters: ['Three Dissenter Leaders (erased)', 'Proto-Warden Commander (remains loyal)'],
    affected_factions: ['Veil Wardens (fractured)', 'Imperial Court'],
    affected_locations: ['Pale Throne', 'Three unnamed cities (ruins)'],
    consequences: 'First known use of the Loom against living people. Creates the Suppression Logs — the secret record Theo Nessian is hiding.',
    canon_status: 'canon',
  },
  {
    id: 'event-03-veilbreak',
    universe_id: DEMO_UNIVERSE_ID,
    title: 'The Veilbreak — The Sky Splits',
    era_marker: 'Year Zero / The Fracture',
    summary: 'Emperor\'s final attempt to complete the Archive fails catastrophically. The Loom overloads. The sky tears open. Ashen Storms are born from the wound. The Empire falls in a single night.',
    affected_characters: ['The Emperor (vanishes)', 'All of Ashenmere (memory disrupted)'],
    affected_factions: ['All (devastated)', 'Solarian Empire (destroyed)'],
    affected_locations: ['The Pale Library (epicenter)', 'Forgetting Wastes (created)', 'Pale Throne (frozen mid-collapse)'],
    consequences: 'Creates the world as it currently exists. Beginning of all current timeline.',
    canon_status: 'canon',
  },
  {
    id: 'event-04-first-survivors',
    universe_id: DEMO_UNIVERSE_ID,
    title: 'The Wandering Century — Survivors Rebuild',
    era_marker: 'Post-Fracture Years 1–100',
    summary: 'The century after the Veilbreak. Small communities form around Storm survivors. The Veil Wardens reorganize as peacekeeping force. The Memory Keepers begin collecting fragments.',
    affected_characters: [],
    affected_factions: ['Veil Wardens (reformed)', 'Memory Keepers (expanded)'],
    affected_locations: ['Threshold (founded)', 'Echo Market (founded)'],
    consequences: 'Establishes the modern power structure. The Wardens and Keepers form their alliance — and the secret pact that becomes the Suppression Logs.',
    canon_status: 'canon',
  },
  {
    id: 'event-05-ashborn-founding',
    universe_id: DEMO_UNIVERSE_ID,
    title: 'The Founding of the Ashborn Guild',
    era_marker: 'Post-Fracture Year 120',
    summary: 'A former Warden named Thessa Ash (Lysa\'s ancestor) establishes the Guild after being expelled for stealing Archive fragments. Her philosophy: "If history belongs to no one, it belongs to everyone."',
    affected_characters: ['Thessa Ash (founder, deceased)'],
    affected_factions: ['Ashborn Guild (founded)', 'Veil Wardens (enemies from founding)'],
    affected_locations: ['Echo Market (Guild establishes control)'],
    consequences: 'Creates the main counter-power to the Warden/Keeper establishment. Lysa carries Thessa\'s original guild-charter.',
    canon_status: 'canon',
  },
  {
    id: 'event-06-shattered-crown-rise',
    universe_id: DEMO_UNIVERSE_ID,
    title: 'The Crowning in Ash — Shattered Crown Declares',
    era_marker: 'Post-Fracture Year 280',
    summary: 'Varro Solane declares himself Emperor-Claimant at the Pale Throne, presenting a bloodline document the Memory Keepers say is forged and the Guild says is real.',
    affected_characters: ['Varro Solane'],
    affected_factions: ['Shattered Crown (declared)', 'Veil Wardens (condemned the claim)', 'Memory Keepers (disputed)'],
    affected_locations: ['Pale Throne'],
    consequences: 'Triggers the current geopolitical crisis. The document\'s authenticity is the central unresolved question of the present era.',
    canon_status: 'canon',
  },
  {
    id: 'event-07-loom-discovered',
    universe_id: DEMO_UNIVERSE_ID,
    title: 'The Loom is Found',
    era_marker: 'Post-Fracture Year 299 — Two Years Ago',
    summary: 'Shattered Crown forces breach Archive Zero (partial discovery) and extract the Solarian Loom — incomplete but functional. All factions respond simultaneously.',
    affected_characters: ['Varro Solane', 'Selara Dusk', 'The Nameless General'],
    affected_factions: ['All major factions'],
    affected_locations: ['Archive Zero (partially breached)', 'Pale Throne (Loom stored here)'],
    consequences: 'The current crisis begins. Every faction mobilizes. Kael is recruited by the Guild.',
    canon_status: 'canon',
  },
  {
    id: 'event-08-mirenne-village',
    universe_id: DEMO_UNIVERSE_ID,
    title: 'The Erasure of Hollowfen',
    era_marker: 'Post-Fracture Year 295 — Six Years Ago',
    summary: 'Memory Keeper scholar Mirenne Ash attempts to use a recovered proto-Loom to restore memories to Storm survivors. The device malfunctions. The village of Hollowfen is erased — not killed, but unmade. No one remembers it existed.',
    affected_characters: ['Mirenne Ash (turned Prophet after this)', 'Theo Nessian (covered it up)'],
    affected_factions: ['Memory Keepers (covered up)', 'Storm Prophets (Mirenne joins)'],
    affected_locations: ['Hollowfen (erased — location unknown)'],
    consequences: 'Creates the Storm Prophet leader. Establishes Theo\'s guilt. Creates the suppressed evidence Lysa is searching for.',
    canon_status: 'canon',
  },
  {
    id: 'event-09-kael-found',
    universe_id: DEMO_UNIVERSE_ID,
    title: 'The Hollow Child — Kael Found in Threshold',
    era_marker: 'Post-Fracture Year 278 — Twenty-Three Years Ago',
    summary: 'A child with no name and no memory is found at the edge of the Forgetting Wastes. High Warden Selara Dusk personally recruits him into the Wardens. She knows who he is. She does not tell him.',
    affected_characters: ['Kael Ashvane (found)', 'Selara Dusk (knows the truth)'],
    affected_factions: ['Veil Wardens'],
    affected_locations: ['Threshold'],
    consequences: 'Establishes Kael\'s arc and the secret Selara carries.',
    canon_status: 'canon',
  },
  {
    id: 'event-10-present-day',
    universe_id: DEMO_UNIVERSE_ID,
    title: 'The Convergence — All Factions Move on the Loom',
    era_marker: 'Post-Fracture Year 301 — Present Day',
    summary: 'With the Loom nearly assembled, all five factions converge on the Pale Throne. Kael, now a Guild operative, has been assigned to either steal or destroy it. He doesn\'t know that doing so may erase the only chance to recover his mother.',
    affected_characters: ['Kael Ashvane', 'Selara Dusk', 'Varro Solane', 'Lysa Thorne', 'Mirenne Ash', 'Theo Nessian'],
    affected_factions: ['All five factions'],
    affected_locations: ['Pale Throne', 'Threshold', 'Pale Library'],
    consequences: 'The story begins here.',
    canon_status: 'canon',
  },
];

export const demoArcs: StoryArc[] = [
  {
    id: 'arc-season-one',
    universe_id: DEMO_UNIVERSE_ID,
    title: 'Season One: The Weight of What Was',
    type: 'season',
    summary: 'The race to reach the Solarian Loom before the Shattered Crown can use it. Kael discovers the Guild has its own agenda. The Veilbreak\'s true cause is revealed.',
    start_point: 'Kael is recruited by the Guild to infiltrate Shattered Crown territory and assess the Loom threat.',
    end_point: 'The Loom is activated — but by the wrong person, for the wrong reason. A small region of history is rewritten. The consequences are not what anyone predicted.',
    involved_characters: ['Kael Ashvane', 'Lysa Thorne', 'Selara Dusk', 'Varro Solane', 'Mirenne Ash'],
    involved_factions: ['Ashborn Guild', 'Veil Wardens', 'Shattered Crown', 'Storm Prophets'],
    themes: ['The price of truth', 'Who owns history', 'Complicity and legacy'],
  },
  {
    id: 'arc-kael-hero',
    universe_id: DEMO_UNIVERSE_ID,
    title: 'Kael\'s Arc: The Man Who Remembered Too Much',
    type: 'hero',
    summary: 'A three-act hero arc centered on Kael\'s journey from amnesiac soldier to the person who must choose between saving one memory (his mother) and preserving the world\'s right to have any memories at all.',
    start_point: 'Kael joins the Guild believing the Loom can restore his mother. He is a weapon looking for purpose.',
    end_point: 'Kael learns his mother chose to be forgotten — to protect him. He must honor that choice or betray everything she sacrificed.',
    involved_characters: ['Kael Ashvane', 'Mirenne Ash', 'Selara Dusk'],
    involved_factions: ['Ashborn Guild', 'Veil Wardens'],
    themes: ['Grief and acceptance', 'Identity without history', 'The difference between memory and love'],
  },
  {
    id: 'arc-prophecy-arc',
    universe_id: DEMO_UNIVERSE_ID,
    title: 'The Unnamed\'s Heir — Prophecy Arc',
    type: 'prophecy',
    summary: 'A long-form arc spanning multiple seasons tracking the prophecy of the Unnamed\'s heir — the figure who can either seal or unravel the Veil entirely.',
    start_point: 'The prophecy is publicly announced by the Storm Prophets as their justification for pursuing the Second Veilbreak.',
    end_point: 'The heir is identified. The choice — seal or unravel — is made. The world is permanently changed.',
    involved_characters: ['The Unnamed Heir', 'Mirenne Ash', 'Kael Ashvane', 'Varro Solane'],
    involved_factions: ['Storm Prophets', 'All factions (react to prophecy)'],
    themes: ['Destiny vs. choice', 'The burden of being chosen', 'What ending means for a broken world'],
  },
];

export const demoLoreRules: LoreRule[] = [
  {
    id: 'lore-veilweaving-cost',
    universe_id: DEMO_UNIVERSE_ID,
    category: 'Magic System',
    title: 'Veilweaving Always Has a Memory Cost',
    description: 'Every act of Veilweaving draws on the weaver\'s own memories as fuel. Minor weaving costs trivial memories (what you ate, a stranger\'s face). Major weaving can cost significant memories — childhood, relationships, identity. The more powerful the weaving, the higher the cost.',
    applies_to: ['Kael Ashvane', 'Selara Dusk', 'Mirenne Ash', 'All Veilweavers'],
    canon_status: 'canon',
  },
  {
    id: 'lore-storm-immunity',
    universe_id: DEMO_UNIVERSE_ID,
    category: 'World Rules',
    title: 'Ashen Storms Cannot Be Redirected — Only Survived',
    description: 'The Ashen Storms follow paths determined by the Veilbreak itself. No known magic can redirect, stop, or destroy them. They can be survived through specific preparation (Storm Prophets know the methods) or by using a Seal-shelter. Attempting to Veilweave inside a Storm accelerates memory consumption by ten times.',
    applies_to: ['Veil Wardens', 'Storm Prophets', 'All inhabitants of Ashenmere'],
    canon_status: 'canon',
  },
  {
    id: 'lore-loom-singularity',
    universe_id: DEMO_UNIVERSE_ID,
    category: 'Artifacts',
    title: 'Only One Complete Loom Can Exist at a Time',
    description: 'The Solarian Loom is not an artifact — it is a wound in the Veil that has been shaped into a tool. Only one fully assembled Loom can function at any time. Lesser proto-Looms (like the one Mirenne used) exist, but they are unstable and cause localized erasures rather than controlled rewrites.',
    applies_to: ['Solarian Loom', 'Varro Solane', 'All Veilweavers'],
    canon_status: 'canon',
  },
  {
    id: 'lore-echo-fragments',
    universe_id: DEMO_UNIVERSE_ID,
    category: 'World Rules',
    title: 'Echo Fragments Carry Residual Consciousness',
    description: 'Echo fragments — shards of pre-Veilbreak knowledge — are not inert objects. They contain residual impressions of the people who created or held them. Trained Veilweavers can read these impressions. Untrained contact with strong Echoes can cause involuntary memory overlaps — briefly experiencing someone else\'s memories.',
    applies_to: ['Kael Ashvane', 'Theo Nessian', 'Pale Library', 'Echo Market'],
    canon_status: 'canon',
  },
  {
    id: 'lore-erased-persons',
    universe_id: DEMO_UNIVERSE_ID,
    category: 'World Rules',
    title: 'Erased Persons Leave Structural Gaps',
    description: 'When someone is erased by the Loom or an Ashen Storm, they do not simply vanish. They leave gaps — unexplained absences in records, people who reference someone they cannot name, architecture built for occupants who are not there. A skilled archivist can find these gaps and, in theory, reconstruct who was erased from the negative space they left behind.',
    applies_to: ['Kael Ashvane (erased mother)', 'Hollowfen (erased village)', 'Three Dissenter Leaders', 'Theo Nessian'],
    canon_status: 'canon',
  },
];
